        //------------------------------------------------------------------------------
        // <auto-generated>
        //    This code was generated from a template.
        //
        //    Manual changes to this file may cause unexpected behavior in your application.
        //    Manual changes to this file will be overwritten if the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        namespace Moq.EntityFramework.Dangerous.Model
        {
            using System;
            using System.Data.Entity;
            using System.Data.Entity.Infrastructure;
            
            public partial class UserContext : DbContext, IUserContext
            {
            
            	public UserContext() : base("name=UsersEntities3")
                {
                }
            	protected override void OnModelCreating(DbModelBuilder modelBuilder)
                {
                    throw new UnintentionalCodeFirstException();
                }
            
            	public IDbSet<User> Users { get; set; }
            
            	        public void SetModified(object entity)
                    {
                        Entry(entity).State = System.Data.EntityState.Modified;
                    }
            
                    public void SetAdded(object entity)
                    {
                        Entry(entity).State = System.Data.EntityState.Added;
                    }
                
            
            }
            
            
            
            }
            	
